[package]
name = "snake-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.7.3"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["ttf", "gfx", "image", "mixer"]
